### ISSUE TITLE
[FEAT]: New plugin idea - sync plugins

### ISSUE THREAD

**Issue by javiavid** [4Source/settings-profiles-obsidian-plugin#14]
### Is your feature request related to a problem?

- [X] The feature should solve a problem.

### Describe the Problem your feature should fix.

If you have several vaults you have to update and configure the plugins in each vault, it is quite annoying.

### Describe the feature you would like to have.

(I know this is not for this plugin, but I think something like this would be very useful for another plugin, I just wanted to convey the idea, I did not know where to do it)

The idea is to have a plugin to synchronize plugins between vaults with an optional option to synchronize configurations.

**Comment by 4Source** [comment]
I am currently working on it. The current version changed a lot but I got some Bugs I need to Fix before releasing it.

**Comment by 4Source** [comment]
If I understood your query correctly then you want to configure a vault with plugins and their settings. And then copy these settings to other vaults. I think the new version [0.2.0](https://github.com/4Source/settings-profiles-obsidian-plugin/releases/tag/0.2.0) include the features you like but I found one major issue with this. Currently the plugin don't imports existing profiles. But I will work on this. If you have any Ideas about that or something else feel free the share your thoughts.

**Comment by javiavid** [comment]
I have tried the plugin and it is great. My idea is to be able to use the profiles from one vault in another.
This is very useful for all vaults to be synchronized with the same configuration if you wish, this would avoid having to download plugin updates in each vault or having to configure them all every time you change something.

It is also very good for testing, for example when testing new plugins, you can change from a profile with your desired configuration to a basic profile with only the testing plugin you need.

**Comment by 4Source** [comment]
Yes im started working on it. I think that shouldn't take that long.

That's right it could be useful for testing.

**Comment by javiavid** [comment]
Is it possible to detect when you close the settings window?
It could also be a good time to save.

I was telling you about the time period because if you implement the ability to use it in several vaults, perhaps this would avoid problems.

**Comment by 4Source** [comment]
I think I got it working. I would appreciate if someone could test it. @javiavid 

Here the plugin files: 
[settings-profiles.zip](https://github.com/4Source/settings-profiles-obsidian-plugin/files/14230686/settings-profiles.zip)

To test just put the folder inside the zip folder in .obsidian/plugin of the vaults. I recommend not using a vaults that is actually used.

**Comment by javiavid** [comment]
Hello, I am attaching a video so you can see the result with the zip you sent.

https://github.com/4Source/settings-profiles-obsidian-plugin/assets/7627504/57918c5a-1486-4b8a-8fed-17d88021b188

The empty one-3plugins folder that is created in the profiles folder is from another test I did before, notice that it only has 1 script (one-3plugins) instead of 2 (one--3plugins).
The strange thing is that this profile was already deleted.

**Comment by 4Source** [comment]
I was able to reproduce it, I'll look into why it creates empty folders from previous profiles. Additionally, it appears that the settings are not being applied correctly. Thanks for your test so far.

**Comment by 4Source** [comment]
Ok, I have a new alpha ready. This should fix the settings not being applied correctly and the ghost folder should also no longer be created.

New version: [settings-profiles_alpha.1.zip](https://github.com/4Source/settings-profiles-obsidian-plugin/files/14234061/settings-profiles_alpha.1.zip)

**Comment by javiavid** [comment]
The theme applies well, but the plugins do not.

https://github.com/4Source/settings-profiles-obsidian-plugin/assets/7627504/99078204-5623-4ef6-9a1c-0542e79225d5

**Comment by 4Source** [comment]
Ok hopefully no more issues 

[settings-profiles_alpha.2.zip](https://github.com/4Source/settings-profiles-obsidian-plugin/files/14236992/settings-profiles_alpha.2.zip)

**Comment by javiavid** [comment]
It works very well!

The only thing I don't understand well is the check, what does it indicate?

Look at what happens in the video, when I try to apply the profile the last time I can't because the check appears instead of the arrow icon to apply.

https://github.com/4Source/settings-profiles-obsidian-plugin/assets/7627504/b88018cf-e500-44b6-8d8f-4c066ecb8d7a

**Comment by 4Source** [comment]
The check mark means that this is the currently selected profile. To reload or save the current profile, you can use the Save Profile button and the Load Profile button above it.
Reloading the profile when making changes from another vault will change in future. Please refer to #17

**Comment by 4Source** [comment]
@javiavid thank you for your testing helped me a lot

**Comment by javiavid** [comment]
Thanks you for the plugin!
