### ISSUE TITLE
[FEAT]: Auto update profile option

### ISSUE THREAD

**Issue by javiavid** [4Source/settings-profiles-obsidian-plugin#17]
### Is your feature request related to a problem?

- [ ] The feature should solve a problem.

### Describe the Problem your feature should fix.

If you are in a profile and you modify the configuration of the plugins it is not saved automatically, if I change the profile I lose the current configuration.

### Describe the feature you would like to have.

A checkbox in the profile selection so that that profile is automatically updated when modifying something within obsidian.

**Comment by 4Source** [comment]
Thanks for your request I know about this problem. But at the moment I don't know how to fixes this problem. I have no event found that gets triggered when settings are changed. I hope I can fix this Issue in the future. I would appreciate if anyone has a idea how to fix. 

For now make sure you press the "Save profile" button before switching profile.

**Comment by javiavid** [comment]
What if before switching to the new profile the current one is saved automatically (according to your auto-save configuration)?

**Comment by javiavid** [comment]
Is it possible to detect when you close the settings window?
It could also be a good time to save.

I was telling you about the time period because if you implement the ability to use it in several vaults, perhaps this would avoid problems.

**Comment by 4Source** [comment]
The best would be to get the event when Obsidian saves the settings. Closing the settings window would also be a good option. I need to read the documentation and code a little more closely to find out if there is a way to detect that settings have been changed or the window has been closed. This doesn't seem to be a basic functionality of the Obsidian plugin interface.

As mentioned, saving would be best if triggered by an event. However, when loading profiles, it might be useful to have a period of time to check for changes in profiles so that the changed settings are reflected when two instances are running in parallel with the same profiles.

**Comment by 4Source** [comment]
I thought about it again and this is what I came up with:

1. When profiles should be saved as discussed above.
> The best would be to get the event when Obsidian saves the settings. Closing the settings window would also be a good option. I need to read the documentation and code a little more closely to find out if there is a way to detect that settings have been changed or the window has been closed. This doesn't seem to be a basic functionality of the Obsidian plugin interface.
- [x] Need to find a event that triggers when settings changed or when settings closed

2. When profiles should be loaded
> However, when loading profiles, it might be useful to have a period of time to check for changes in profiles so that the changed settings are reflected when two instances are running in parallel with the same profiles.

The problem I have with this approach is that Obsidian needs to be reloaded for changes in the settings to take effect and when this keeps happening it's very annoying. 
- [ ] Option 1: Use a interval based reload and first comparing the files and if nothing has changed, nothing is loaded.
- [ ] Option 2: Include paths to vaults where there are active and update the files in the save process. Problem opened vaults don't know that they need to reload.  

If any other ideas I wish to hear them.

**Comment by javiavid** [comment]
I've been thinking about it and I think a way to simplify the loading could be something like the workspaces plus plugin https://github.com/nothingislost/obsidian-workspaces-plus. In case a profile has changed in another vault, it may appear red and when pressed it updates.

Maybe you have to take into account that there may be conflicts with the auto save if you have 2 open vaults... I don't know, I think the workspace system is simple and you will avoid problems.

I give you an example of conflict:
- Open vault 1
- Open vault 2
- You modify some configuration in 1.
- You change to the vault 2 window and without being updated you change something in the configuration.
- What profile is the good one now? ..

**Comment by 4Source** [comment]
Also a good option

**Comment by 4Source** [comment]
@javiavid 
I have added a new pre-release version. This contains parts of the features discussed here. You can test it with the BRAT plugin.

How to BRAT: 
1. "Add Beta plugin with frozen version" 
    - https://github.com/4Source/settings-profiles-obsidian-plugin
    - 0.5.0-beta.0

**Comment by javiavid** [comment]
Thanks
I can't get it to update from one vault to another automatically, how does it work?

**Comment by javiavid** [comment]
It also seems that it does not save the plugin configuration well. I attached a test.

https://github.com/4Source/settings-profiles-obsidian-plugin/assets/7627504/59e4e939-20b3-4f37-80ab-499a836eab9b

**Comment by 4Source** [comment]
The auto save and reload is currently not included. But i added a status bar Icon that currently displays the profile is up-to-date you can click on that to reload. The save needs to be done manually in settings. But now you there is at least a way you can see the profile is up-to-date. Sorry, I should have said that more clearly.

**Comment by javiavid** [comment]
No problem, it's great to have it in the status bar, I think it's very convenient, although I think it doesn't work well or maybe I did something wrong. I attached a video.

https://github.com/4Source/settings-profiles-obsidian-plugin/assets/7627504/722a3263-2c66-4bbc-806e-f011777c738c

**Comment by 4Source** [comment]
Interesting I will take a look at it. Can you tell me the name of the plugin you are using

**Comment by javiavid** [comment]
File Color

**Comment by 4Source** [comment]
Added new Beta 

Change BRAT to:
- https://github.com/4Source/settings-profiles-obsidian-plugin
- 0.5.0-beta.1

**Comment by 4Source** [comment]
Actually you should test this version directly, I have the autoSync feature implemented. Loading doesn't happen by itself, but I think it's better that way.

Change BRAT to:
- https://github.com/4Source/settings-profiles-obsidian-plugin
- 0.5.0-beta.2

**Comment by 4Source** [comment]
No problems found on your side?

**Comment by javiavid** [comment]
No, at least for now, it is true that I have not spent much time testing with work, but for now I have it in some test vaults in case something strange happens.

Maybe it would be good to launch it in the community and have more people try it.

**Comment by 4Source** [comment]
I think this will happen during the day I need to do small changes
