### ISSUE TITLE
[FEAT]: Theme configuration in the profile

### ISSUE THREAD

**Issue by javiavid** [4Source/settings-profiles-obsidian-plugin#18]
### Is your feature request related to a problem?

- [ ] The feature should solve a problem.

### Describe the feature you would like to have.

When you save a profile your theme settings are also saved. This way the profile would be even more complete.

**Comment by 4Source** [comment]
![image](https://github.com/4Source/settings-profiles-obsidian-plugin/assets/38220764/3a7b0cd5-f7a8-49d6-a5b5-b0bc645db7b9)

Do you mean these?

**Comment by javiavid** [comment]
yes

**Comment by javiavid** [comment]
Thanks

**Comment by Universal-Invariant** [comment]
The them is not syncing on my end. On the alternate vault there are no themes(I haven't installed any) so it isn't copying over the themes. So if the plugin is just setting the theme then it doesn't quite work(it should copy it over or at least throw an error to the user).
