### ISSUE TITLE
[Bug]: Other profiles not visible in the other vaults

### ISSUE THREAD

**Issue by N3C2L** [4Source/settings-profiles-obsidian-plugin#23]
### Describe the bug

The other profiles are not visible in the other vaults.

### How to Reproduce

Hello,

I am on Windows 10.
I created 2 profiles for 2 different vaults.
Here: "..Documents\Obsidian\Profiles"
But in the plugin settings only one profile is visible in vault 1.
And in vault 2 again only one profile is visible.
But there should be 2 profiles visible in every vault for switching profiles, am I right?
Is the "Reload Profiles" button working on your site?
I looked into my hard drive path for the profiles, and both profiles are visible there! But not in Obsidian in your settings plugin page.
I even created a new vault but with the same result.

### Expected behavior

Profiles should be visible in every vault.

### OS of your device

Win10

### Obsidian Version

1.5.3

### Plugin Version

0.3.0

**Comment by 4Source** [comment]
This is related to #14

**Comment by 4Source** [comment]
Actually it should copy the plugins but at the alpha it seem that not all settings get synchronized correctly. All other settings work correctly for you?

**Comment by 4Source** [comment]
Does the new alpha fix it? https://github.com/4Source/settings-profiles-obsidian-plugin/issues/14#issuecomment-1937869689

**Comment by 4Source** [comment]
I am glad to hear that. 
I already thought about a feedback for the save and load button this shouldn't be that hard.
