### ISSUE TITLE
[Bug]: Changing "Profile" path in settings create a recursive duplications o a the current "profile" folder, do to the depth >100 folder

### ISSUE THREAD

**Issue by MMitsialis** [4Source/settings-profiles-obsidian-plugin#30]
### Describe the bug

Edit the path in "Profile folder" location, then press change. 
The contents of that folder are then copied into a path going down over 100 directories deep.

### How to Reproduce

1. Using Windows with the "Profile" directory in my 'local" OneDrive folder:  C:\users\marcm\OneDrive\Obsidian\Profile
2. I have one profile "Common"
3. Change path to "C:\users\marcm\OneDrive\Obsidian\SettingsProfile"
4. The contents of "C:\users\marcm\OneDrive\Obsidian\Profile\Common" are copied recursively into "C:\users\marcm\OneDrive\Obsidian\Profile\Common" to de depth of > 100. I killed the process as Obsidian stopped repsonding. 

- I have tried this on three different vaults the same thin happens. OneDriver start complaining when the path exceed 255 characters. 
- Trying to clean-up with the "File Explore" doesn't it just freezes. 
- Cleaning using another file manager crashes when the path length exceeded 1022 character. 
- I had to "go offline" , make a copy of the folder on OneDrive Online. 
- Boot my computer off a Linux Live CD, then delete the local folder. Windows GUI apps seem to be incapable of dealing with the path of this length. 

### OS of your device

Windows 10

### Obsidian Version

1.5.3

### Plugin Version

0.4.1

**Comment by 4Source** [comment]
Sry for that I will take a lock at that
