### ISSUE TITLE
[Bug]: Unable to save initial profile

### ISSUE THREAD

**Issue by abaljeu** [4Source/settings-profiles-obsidian-plugin#32]
### Describe the bug

The value for profile location is C:\Users\Windows\Documents\Obsidian\Profiles.  This only exists and is accessible if the computer is windows, has an account named windows and that user is active.  On this computer, the folder doesn't exist.  I am unable to change it or to create a profile on this machine.

### How to Reproduce

It probably came about because Dropbox sync copied everything from another computer which had this directory.  But now that folder is inaccessible, the field can't successfully be edited.

### OS of your device

Win10

### Obsidian Version

v1.5.3

### Plugin Version

0.4.1

### Additional context

I am experimenting to see if I can get C:\Obsidian\SettingsProfiles to be a usable profile directory.

**Comment by 4Source** [comment]
Could you try the new Version [0.4.2](https://github.com/4Source/settings-profiles-obsidian-plugin/releases/tag/0.4.2) I have made some changes to profiles path may it also fixed your problem.
