### ISSUE TITLE
[Bug]: Can't load Profiles, Empty Profile list

### ISSUE THREAD

**Issue by AlexKrew** [4Source/settings-profiles-obsidian-plugin#40]
### Describe the bug

I can save profiles, but I cannot load or even see them is the Profile List.
Tested: 
- Using predefined and custom Path
- Using main and sandbox Vault
- Restarting
- Overwriting existing Profile

### How to Reproduce

1. Open Sandbox Vault or Private Vault (Tested both)
2. Install Plugin
3. Save Settings
4. Nothing to see in the List

### OS of your device

MacOs Sonoma 14.2.1 (23C71)

### Obsidian Version

Version 1.5.8 (Installer 1.4.16)

### Plugin Version

0.5.1

### Additional context

I get this Error when saving a Profile
<img width="426" alt="Screenshot 2024-02-25 at 18 15 02" src="https://github.com/4Source/settings-profiles-obsidian-plugin/assets/102223870/be71d200-54a7-4a0d-940a-c5f375287109">

This is the saved Profile:
<img width="580" alt="Screenshot 2024-02-25 at 18 20 12" src="https://github.com/4Source/settings-profiles-obsidian-plugin/assets/102223870/315f516d-4809-40d0-b80d-67d00d6991e3">

And this is the profile.json:
```
{
  "name": "Test-Profile",
  "autoSync": true,
  "appearance": true,
  "app": true,
  "bookmarks": true,
  "communityPlugins": true,
  "communityPluginsAdvanced": {},
  "corePlugins": true,
  "graph": true,
  "hotkeys": true,
  "modifiedAt": "2024-02-25T17:13:34.718Z"
}
```

**Comment by 4Source** [comment]
This seems only to appear on mac I will try it on vm. The created profile folder looks good just like the profile.json. 
- When your reloading Obsidian you don't get any errors? 
- Do you have the permissions for the folder? 
- Have you installed any other plugins?
- How do you have created profile via Command or in Settings?

By the way there is a command to reload Obsidian if you didn't know. ``Reload app without saving``

**Comment by AlexKrew** [comment]
This happens when I save the Profile. 
In both cases (Profile exists already, Profile does not exist).
This is the only Error I get. 
![Screenshot 2024-02-26 at 14 55 59](https://github.com/4Source/settings-profiles-obsidian-plugin/assets/102223870/8399db09-b937-401c-8670-2fcb3937fb66).

Yes, Obsidian has Permission to this folder
I have some others, but I also tried it on an Empty and Sandbox Vault.
I create the Profile with the Settings UI.

This is from the new Version

**Comment by 4Source** [comment]
I created a new pre-release version so you could test it before I mark this issue as fixed. To install this pre-release you will need the BRAT plugin, you can download it in Obsidian. 
In the BRAT Settings go down to the Button "Add Beta plugin with frozen version" in the window enter:
Repository: ``https://github.com/4Source/settings-profiles-obsidian-plugin``
Release version: ``0.5.3-beta.0``

I'm sorry you have to take the time to test it yourself. Unfortunately the installation of the vm does not work.

**Comment by AlexKrew** [comment]
I found the Bug.

In `FileSystem.ts` `getAllFiles()` you check for the path to have `\*\` (There are some more occurrences of Backslashes). Which only works for Windows.

I tested it with `/*/`, works like a charm.
You should use something like `path.sep` for the Path separators.

![Screenshot 2024-02-26 at 20 39 35](https://github.com/4Source/settings-profiles-obsidian-plugin/assets/102223870/8b7fcd03-5731-47a5-b277-104e162d4753)

**Comment by 4Source** [comment]
I didn't even know that. Thanks, that would probably have taken me a while to find. I think I got all of the path separators. I have added a new Beta could you test it on mac?

Version: ``0.5.3beta.1``

**Comment by AlexKrew** [comment]
There is still a bug left in `FileSystem.ts` `getAllFiles`.

If the `path` prop is `['/Users/.../Test-Vault', '.obsidian', 'themes/*/*']`. The marked section in the image below assumes every child of `themes` is another folder. `themes` should have no single file, but macOS folders can have a `.DS_Store` file, which is used for storing folder properties.
So you need to check whether it is a folder or not.

Maybe it is better to not use `/*/*` and just recursively copy everything.
Then you could just avoid a folder or file with a blacklist.

![Screenshot 2024-02-27 at 00 53 35](https://github.com/4Source/settings-profiles-obsidian-plugin/assets/102223870/b1f03081-2424-4cf9-b8ab-6f45c844577c)

**Comment by 4Source** [comment]
Does not copying this file cause problems? Since this should only contain system information.

**Comment by AlexKrew** [comment]
I never really worked with `.DS_Store` files. But what I read is that you should prevent copying this file.

**Comment by 4Source** [comment]
Ok, I think I misunderstood it, I thought you wanted this file to be copied too. But so I can simply add a general ignore file list.

**Comment by 4Source** [comment]
Added the changes to ``0.5.3-beta.2``

**Comment by 4Source** [comment]
@AlexKrew Could you test the new version?

**Comment by AlexKrew** [comment]
Hey, yes, of course. I had a full schedule, I will test it tomorrow.

**Comment by 4Source** [comment]
Added the changes to ``0.5.3-beta.3`` 
I hope this resolves the issues. It's really annoying that I can't test it myself.

**Comment by AlexKrew** [comment]
Yes, now it is working perfectly. Thank you so much for the quick fix. 
I think testing on Linux could be helpful. It has some similarities to macOS regarding file structure.

**Comment by AlexKrew** [comment]
But I have one last thing. Would it be possible to implement a toggle to opt-out of the automatic refresh of the Refresh Interval? I would much rather only save manually. Because every 100–5000 ms, the plugin reads every single file from the `.obsidian` folder, even if there are no settings changes.
