### ISSUE TITLE
[Bug]: Default directory is always created on install

### ISSUE THREAD

**Issue by kazmath** [4Source/settings-profiles-obsidian-plugin#49]
### Describe the bug

I am starting to use obsidian more lately and this plugin has helped a lot with creating a reproducible pattern between vaults, but every time I install it in a different vault, the `~/Documents/Obsidian` directory gets created, so I end up with two "Documents" directories in my home, my localized "`~/Documentos`" directory and this plugin's "`~/Documents`".

### How to Reproduce

1. Create vault
2. Install plugin
It then creates `~/Documents` regardless if I will use it or not

### Expected behavior

It should either use the [XDG specification](https://xdgbasedirectoryspecification.com/) or have no default directory at the very least. I don't expect you to adopt XDG specs, but I will say that `~/.local/share/Obsidian/Profiles` is much more clean than `~/Documents/Obsidian/Profiles`.

But for the purposes of this bug report, I think at least removing the hardcoded, non-localized, `~/Documents` default path and replacing it with literally anything else (XDG spec/somewhere inside the vault/nothing at all) is fine.

### OS of your device

Linux (Pop OS)

### Obsidian Version

v1.5.12

### Plugin Version

v0.5.6

**Comment by 4Source** [comment]
I have Fixed the Bug. I use the XDG specification It should use the ``XDG_DATA_HOME`` with a Subdirectory ``/ObsidianPlugins``.

I have released a Beta version [0.5.7-beta.0](https://github.com/4Source/settings-profiles-obsidian-plugin/releases/tag/0.5.7-beta.0) of it so could you please test it is working for you?

You could install it manually or I can recommend another plugin of mine it is called [VARE](https://obsidian.md/plugins?id=vare). This adds support for beta versions installation.

**Comment by kazmath** [comment]
I installed it using VARE (great plugin btw) in a brand new vault and all the changes you mentioned seem to be working fine in my system. I will just have to migrate my old profiles to the new default directory. Thanks for the incredibly quick reply and solution.
